### Grid Problem - MDP

In [19]:
import numpy as np
import random

In [20]:
# Grid Initialization
grid_size = 100
grid = np.zeros((grid_size, grid_size))

In [21]:
print(grid)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [22]:
# Obsticle Initialization - Randomly place obstacles in the grid
num_obstacles = int(grid_size * grid_size * 0.2)  
for _ in range(num_obstacles):
    x, y = random.randint(0, grid_size-1), random.randint(0, grid_size-1)
    grid[x, y] = -1 

In [23]:
print(grid, grid.shape)

[[ 0.  0.  0. ...  0. -1.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [-1.  0.  0. ...  0. -1. -1.]
 ...
 [-1. -1.  0. ... -1.  0. -1.]
 [ 0. -1.  0. ...  0.  0.  0.]
 [ 0.  0. -1. ...  0. -1.  0.]] (100, 100)


In [24]:
# Start and Goal Initialization
start = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))
end = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))
while grid[start] == -1:
    start = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))
while grid[end] == -1:
    end = (random.randint(0, grid_size-1), random.randint(0, grid_size-1))

In [25]:
# MDP components
actions = ['up', 'down', 'left', 'right']
action_effects = {
    'up': (-1, 0),
    'down': (1, 0),
    'left': (0, -1),
    'right': (0, 1)
}
gamma = 0.9  # Discount factor
alpha = 0.1  # Learning rate
epsilon = 0.1  # Exploration rate

In [26]:
# Q-table
Q = np.zeros((grid_size, grid_size, len(actions)))

In [27]:
def choose_action(state):
    if random.uniform(0, 1) < epsilon:
        return random.choice(actions)
    else:
        return actions[np.argmax(Q[state[0], state[1]])]

In [28]:
def take_action(state, action):
    effect = action_effects[action]
    next_state = (state[0] + effect[0], state[1] + effect[1])
    if 0 <= next_state[0] < grid_size and 0 <= next_state[1] < grid_size and grid[next_state] != -1:
        return next_state
    else:
        return state

In [29]:
def get_reward(state):
    if state == end:
        return 100
    elif grid[state] == -1:
        return -100  
    else:
        return -1  

In [30]:
# Training the agent
num_episodes = 1000
for episode in range(num_episodes):
    state = start
    while state != end:
        action = choose_action(state)
        next_state = take_action(state, action)
        reward = get_reward(next_state)
        Q[state[0], state[1], actions.index(action)] = Q[state[0], state[1], actions.index(action)] + alpha * (reward + gamma * np.max(Q[next_state[0], next_state[1]]) - Q[state[0], state[1], actions.index(action)])
        state = next_state

In [31]:
# Policy evaluation
policy = np.zeros((grid_size, grid_size), dtype=str)
for i in range(grid_size):
    for j in range(grid_size):
        policy[i, j] = actions[np.argmax(Q[i, j])]

In [32]:
print(policy)

[['d' 'd' 'l' ... 'r' 'u' 'r']
 ['l' 'd' 'r' ... 'r' 'r' 'r']
 ['u' 'd' 'u' ... 'u' 'u' 'u']
 ...
 ['u' 'u' 'l' ... 'u' 'r' 'u']
 ['u' 'u' 'd' ... 'u' 'd' 'u']
 ['u' 'u' 'u' ... 'r' 'u' 'r']]
